### PR TITLE
chore: update doc links from googleapis.dev to cloud.google.com

### PR DESCRIPTION
**Pull request by dandhlee**
Updating the reference documentation website from googleapis.dev to cloud.google.com for the index pages. Also updating references in the README.

### CODE REVIEW

**Comment by daniel-sanche** [comment]
Is googleapis.dev being deprecated? Because there's a lot of useful information there that's not on cloud.google.com. Can we mirror the [usage guide](https://googleapis.dev/python/logging/latest/usage.html)?

**Comment by dandhlee** [comment]
googleapis.dev won't be deprecated. Usage guide exists in: https://cloud.google.com/python/docs/reference/logging/latest/usage

**Comment by daniel-sanche** [comment]
Do we have the ability to modify those pages? Maybe edit the [Overview page](https://cloud.google.com/python/docs/reference/logging/latest) to link to the usage guide and other important places in the docs?

**Comment by dandhlee** [comment]
I plan on merging the current overview page and the content we have for googleapis.dev/README from the github! Feel free to leave this out unmerged until that change is made and https://github.com/googleapis/sphinx-docfx-yaml/issues/106 is closed.

**Comment by dandhlee** [comment]
There will be a bulk approval going through, I'll close this issue for now until the issue on the plugin repo is resolved.

**Pull request closed without merging**
