### PR TITLE
feat: add logic to convert severity string to uppercase 

### LINKED ISSUE #743: Convert `severity` string to uppercase in `Batch#log_struct`
**Is your feature request related to a problem? Please describe.**

As discussed in #739, currently `log_struct` for `Batch` cause type error when the log level is passed in `str` to `severity` argument. To align with [the document](https://cloud.google.com/python/docs/reference/logging/latest/entries) and usability, it's great to have some mechanism to convert `str` to appropriate Enum value. 

 **Describe the solution you'd like**

Apply some logic to convert `str` data to Enum like [what has done for `log` function](https://github.com/googleapis/python-logging/blob/440d3f634b69991100ead96d461d3ce83cb7f009/google/cloud/logging_v2/logger.py#L144)

 **Describe alternatives you've considered**

Change description of the document. (ref. #739)

 **Additional context**

#739 #741

### PR DESCRIPTION
**Pull request by ymotongpoo**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [X] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-logging/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Ensure the tests and linter pass
- [X] Code coverage does not decrease (if any source code was changed)
- [X] Appropriate docs were updated (if necessary)

Fixes #743

### CODE REVIEW

**Comment by daniel-sanche** [comment]
This looks great! Would you mind adding a test for this too though, since the bug must have slipped through with the existing tests?

**Comment by ymotongpoo** [comment]
@daniel-sanche I added a small unit test to check if `Batch#commit()` can properly convert severity strings.

**Review by daniel-sanche — APPROVED** [review]
LGTM, thanks!

**Comment by daniel-sanche** [comment]
You can ignore the environment test failures. It looks like I need to upgrade the pandas version there, I'll address that in a separate PR

It looks like there's a lint issue on the Kokoro check before this can be merged though

**Comment by ymotongpoo** [comment]
I just ran `nox` and the result was the following (my local doesn't have Python 3.7, so unit-3.7 didn't run):

```
nox > Session docs was successful.
nox > Ran multiple sessions:
nox > * unit-3.7: failed
nox > * unit-3.8: success
nox > * unit-3.9: success
nox > * unit-3.10: success
nox > * unit-3.11: success
nox > * system-3.8: success
nox > * cover: success
nox > * lint: success
nox > * lint_setup_py: success
nox > * blacken: success
nox > * docs: success
```

I hope this fix works.

**Comment by daniel-sanche** [comment]
looks great, thanks!

**Pull request merged**
