### PR TITLE
feat!: Add option to omit logging.StreamHandler during setup

### LINKED ISSUE #38: Add option to omit `logging.StreamHandler` during setup
This issue is in regards to the `setup_logging` method on the `google.cloud.logging.Client`.

### Is your feature request related to a problem? Please describe.

The problem is that my logs are getting duplicated.

```py
import google.cloud.logging
client = google.cloud.logging.Client()
client.setup_logging()
```

When I follow the simple example in [the docs](https://cloud.google.com/logging/docs/setup/python#connecting_the_library_to_python_logging) to connect my root logger to GCP logging, it sets up 2 handlers, a `logging.StreamHandler` and a `google.cloud.logging.handlers.CloudLoggingHandler`. This is often very reasonable. However, it is causing problems in my case because I also have [this set up](https://cloud.google.com/monitoring/kubernetes-engine/installing#migrating) to send ALL container logs to cloud logging.
The result is a duplication of my logs, one copy from the python root logger, and another copy getting picked up from stderr. (Note that the copy coming from stderr always has its level set to ERROR). This is a problem because the logs are much noisier than needed, causing them to be less useful.

#### Why not change the **Stackdriver Kubernetes Engine Monitoring** option in your cluster?

I currently have it set to **System and workload logging and monitoring**. I *could* set it to **System logging and monitoring only** instead, which will prevent *this pod's* logs from being duplicated. However, there are other, simpler pods that do not have cloud logging set up. I need all of their logs to be captured, not just the pods for which cloud logging is configured. However, once cloud logging **is** configured, I want it to go through the `CloudLoggingHandler` because it has advantages like setting the correct log level, and I don't want the logs to be duplicated.

### Describe the solution you'd like

My issue is with the implementation of [this method](https://github.com/googleapis/python-logging/blob/c6eb60179d674dfd5137d90d209094c9369b3581/google/cloud/logging/handlers/handlers.py#L152). I would like an option that prevents this line `logger.addHandler(logging.StreamHandler())` from happening. Perhaps a new argument like `client.setup_logging(stream_handler=False)`.

### Describe alternatives you've considered

This is my current workaround

```py
from google.cloud import logging as gcp_logging
from google.cloud.logging.handlers import CloudLoggingHandler, ContainerEngineHandler

logging_client = gcp_logging.Client(project=PROJECT_ID)

logging_client.setup_logging(log_level=level)
root_logger = logging.getLogger()
# use the GCP handler ONLY in order to prevent logs from getting written to STDERR
root_logger.handlers = [handler
                        for handler in root_logger.handlers
                        if isinstance(handler, (CloudLoggingHandler, ContainerEngineHandler))]

```

### Additional context

Here is a screenshot of the console showing my duplicated logs:
Screen Shot 2020-05-04 at 5 11 32 PM

### PR DESCRIPTION
**Pull request by ZeJ0hn**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [X] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-logging/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Ensure the tests and linter pass
- [X] Code coverage does not decrease (if any source code was changed)
- [X] Appropriate docs were updated (if necessary)

Fixes #38  🦕

### CODE REVIEW

**Comment by Daniel-Sanche** [comment]
Thanks for the contribution. This is something I've been looking at, but I'm still in the information gathering phase. My impression so far is that the extra handler is needed for some environments (AppEngine?), but causes duplicate entries in others (GKE). I think I'd rather fix the library's logic to add the handler only when appropriate, rather than make it user-optional. But I'm trying to improve the test coverage first to make sure that I can do that without breaking any environments

What do you think? I'm interested in hearing your experiences as a user of the library

**Comment by ZeJ0hn** [comment]
Hi, my experience is very simple : "Why do I have my logs duplicated ???"
It's very confusing to have this `StreamHandler` by default, especially because there is no mention about it in the documentation, and once you discover it, there is no way to disable it (except by filtering manually all handlers).
What I expect from a library is to do exactly what it is made for: in this case, send logs into Stackdriver.

A StreamHandler can be useful in some case (debug in local, etc) but I would prefer to add it myself, because I know that I need it.

From my point of view, for this case, the best should be to simply remove the `StreamHandler` and let the user add one if he needs it.
An intermediate solution is with the arguments `stream_handler=False` because the user is able to have the control on it.

I don't like the solution to disable or not the `StreamHandler` function of the environment because I think the library should have the same behavior everywhere.

Here's my point :-)

**Comment by Daniel-Sanche** [comment]
> From my point of view, for this case, the best should be to simply remove the StreamHandler and let the user add one if he needs it.

I agree, so my plan is to remove the extra StreamHandler entirely, rather than keeping it as an optional argument. I'm going to close this PR for now, but I'll prioritize this fix. We're on release freeze now due to the long weekend, but you can expect to see the fix in the next couple weeks

**Comment by ZeJ0hn** [comment]
@Daniel-Sanche I can remove the handler and push a PR if you want.
I'm happy to help :-)

**Comment by Daniel-Sanche** [comment]
Thanks for the offer, but I just opened this one-liner here: https://github.com/googleapis/python-logging/pull/106. I ran through some manual tests, and couldn't see any issues with just removing the extra handler

If you run into any more bugs while using the library, future bug reports and PRs are appreciated though!
 Thanks

**Pull request closed without merging**
