### PR TITLE
chore: use conventional commits for rennovate bot

### PR DESCRIPTION
**Pull request by daniel-sanche**
update rennovate.json to use chore prefix for PRs

### CODE REVIEW

**Comment by tseaver** [comment]
@daniel-sanche Ugh, Owlbot reverted your change.

**Comment by parthea** [comment]
@daniel-sanche @tseaver I've added a replacement in owlbot.py. PTAL

Once we're happy that the change is working in this repo, we can apply it across all googleapis python repos by updating the templates here:
https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/python_library/renovate.json#L8

**Comment by parthea** [comment]
@googlebot I consent.

**Review by parthea — APPROVED** [review]

**Comment by daniel-sanche** [comment]
Thanks, I forgot about the owlbot complications! I'll merge this after the tests pass

**Pull request merged**
